name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install NASM
        run: sudo apt-get update && sudo apt-get install -y nasm

      - name: Build
        run: make

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install NASM
        run: sudo apt-get update && sudo apt-get install -y nasm

      - name: Test
        run: make test
